
@echo off
echo [+]Connectinto to Network...
echo [+] try to add node %1...
curl --header "Content-Type: application/json" --request POST --data "{\"node_address\":\"%1\"}" --url http://192.168.1.5:8001/register_with