
@echo off
echo [+]Connectinto to Network...
echo [+] try to add node %1...
curl --header "Content-Type: application/json" --request POST --data "{\"node_address\":\"%1\"}" --url https://node-blockchain-1.herokuapp.com/register_with
